### ISSUE TITLE
Set Role Command

### ISSUE THREAD

**Issue by conaticus** [conaticusgrp/boolean#10]
Roles types (todo):
- Moderator

### `/set role [role_type:select] [role:role]`
- A provided list of config roles will be provided (e.g a "moderator" role or "member" role)
- That roleshould be provided before neccessary features/commands can be used for that role
- This will be saved for a specific server in the database

**Comment by ImKventis** [comment]
I'll work on this <3

**Comment by ImKventis** [comment]
Reasoning for "Moderator" role type? Feels a lil like we are reinventing the wheel since discord already has permissions on roles.

**Comment by conaticus** [comment]
> Reasoning for "Moderator" role type? Feels a lil like we are reinventing the wheel since discord already has permissions on roles.

It would be useful for when commands are limited to moderator only so we know which role to allow (though admin permission will be included too). Its difficult to know which permissions moderators will have. With that said this will be a bit limiting, maybe in future we will make permissions more configurable

**Comment by ImKventis** [comment]
Hmm, that's true. I suppose you're imagining something similar to pancakes permissions system? It wouldn't be overly difficult to implement by using some bitflags enums.
I was already considering creating another table for the roles, so it shouldn't be troublesome to improve the roles system later on.
For now, I'll just add two special roles: "Moderator" and "Admin".

**Comment by conaticus** [comment]
> Hmm, that's true. I suppose you're imagining something similar to pancakes permissions system? It wouldn't be overly difficult to implement by using some bitflags enums.
> I was already considering creating another table for the roles, so it shouldn't be troublesome to improve the roles system later on.
> For now, I'll just add two special roles: "Moderator" and "Admin".

Yeah for now we shall keep it to Discord Timeout permission

**Comment by conaticus** [comment]
We're changing how this system works.
