### ISSUE TITLE
Whois Command

### ISSUE THREAD

**Issue by conaticus** [conaticusgrp/boolean#12]
Command now completed with #34, just need a warning system now for:
  - Warning count - and prompt for #11 `/warning history` command to see more info

**Comment by InfinityDevTech** [comment]
Ill snatch this one.

**Comment by InfinityDevTech** [comment]
PR: #34

**Comment by conaticus** [comment]
Solved [3b43f7d](https://github.com/conaticusgrp/boolean/commit/3b43f7d0cfbf68df913334c788115c5fa4eace8f)
