### ISSUE TITLE
Starboard System

### ISSUE THREAD

**Issue by conaticus** [conaticusgrp/boolean#14]
A starboard system where if a message receives the starboard threshold reactions of a "⭐" emoji, the message will be sent to the starboard channel.

### `/set starboard threshold [threshold:number]`
- Admin only
- Do not allow minus numbers or decimals (if discord does allow them), do not accept zero
- Sets in the database the threshold for the number of "⭐" reactions a message is required to receive before it gets posted in the starboard channel

### On reaction event
- If reacted with a "⭐", and the threshold has been reached, send this message to the starboard channel, containing a link to the original message, and the number of "⭐"s it received
- If the message has already been sent, do not resend it but update the message to contain the number of star reactions that message now has

**Comment by ImKventis** [comment]
I'll work on this <3

**Comment by ImKventis** [comment]
Maybe an idea to remove the "threshold" argument, seems pointless.

**Comment by conaticus** [comment]
Solved #57
