### ISSUE TITLE
Member welcomes

### ISSUE THREAD

**Issue by conaticus** [conaticusgrp/boolean#30]
Automated welcome messages with customisable channel with #2
`/set joinrole [Role]` - optional, if set new members will be assigned this role
`/unset joinrole`

**Comment by ImKventis** [comment]
Move channel customization to #2?

**Comment by conaticus** [comment]
> Move channel customization to #2? 

yep will make that more clear, thanks.

**Comment by InfinityDevTech** [comment]
When @ImKventis is done with #2 I will take this.

**Comment by ImKventis** [comment]
Just waiting for #35 to merge. You can view my develop branch if you want to work on it now.

**Comment by ImKventis** [comment]
Scratch that, I am making changes to #35.

**Comment by conaticus** [comment]
@InfinityDevTech this is now ready to work on

**Comment by InfinityDevTech** [comment]
> @InfinityDevTech this is now ready to work on

Alright, Give me a day or two, I have work tomorrow but on wednesday it should be good.

**Comment by conaticus** [comment]
Mine :)

**Comment by InfinityDevTech** [comment]
Dawg, this is MINE
