### ISSUE TITLE
Pagination Module

### ISSUE THREAD

**Issue by conaticus** [conaticusgrp/boolean#32]
A reusable pagination module that can be used for commands such as #11.

**Comment by InfinityDevTech** [comment]
Your making the warning system, I think you can get this underway and I will make it more modular after the fact.

**Comment by conaticus** [comment]
This is still open if anyone wants it, I'll take it if it's not done by the time I get to it (will comment here so y'all know I've taken it)

**Comment by conaticus** [comment]
I'll snatch this

**Comment by conaticus** [comment]
Solved #52
