### ISSUE TITLE
Help Command & Hello Message

### ISSUE THREAD

**Issue by conaticus** [conaticusgrp/boolean#43]
A `/help` command that lists all configurable commands, how to configure them and what they do.

A more brief message will be sent by the bot when it joins a new server (will be sent into the default channel and should ideally ping the bot inviter).

**Comment by ImKventis** [comment]
![image](https://github.com/conaticusgrp/boolean/assets/93383833/f993c3ec-cefb-4501-a2e1-4569d2c5de51)

**Comment by ImKventis** [comment]
I think it might be a better idea to have the on-join message to be briefer than /help rather than re-using. What do you think?

**Comment by conaticus** [comment]
> I think it might be a better idea to have the on-join message to be briefer than /help rather than re-using. What do you think?

Yeah no prob let's do that.

**Comment by conaticus** [comment]
completed in #49
