### ISSUE TITLE
Repeat Command

### ISSUE THREAD

**Issue by conaticus** [conaticusgrp/boolean#8]
- Admin only
- Repeats the message the user sent, with option of attatchments
- Does not allow role/everyone/here pings

**Comment by ImKventis** [comment]
Is this intended to function similar to a 'say' command, or are we snooping at deleted messages?

**Comment by conaticus** [comment]
> Is this intended to function similar to a 'say' command, or are we snooping at deleted messages? 

Yeah, just repeating executor messages

**Comment by conaticus** [comment]
solved [13b1807](https://github.com/conaticusgrp/boolean/commit/13b18070fee8489533bda0da0f59e46f83253ec0)
